"""avec equip

Revision ID: 00537577e855
Revises: ff0315c51567
Create Date: 2021-12-30 19:15:13.174226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00537577e855'
down_revision = 'ff0315c51567'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Num_equi', sa.String(length=15), nullable=True),
    sa.Column('Wc_Descr', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('equip', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_equip_Num_equi'), ['Num_equi'], unique=False)
        batch_op.create_index(batch_op.f('ix_equip_Wc_Descr'), ['Wc_Descr'], unique=False)

    with op.batch_alter_table('sched', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Comment', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('Equip_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_sched_Comment'), ['Comment'], unique=False)
        batch_op.create_foreign_key(None, 'equip', ['Equip_id'], ['id'])

    with op.batch_alter_table('workorder', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Basic_Start', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_workorder_Basic_Start'), ['Basic_Start'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workorder', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workorder_Basic_Start'))
        batch_op.drop_column('Basic_Start')

    with op.batch_alter_table('sched', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_sched_Comment'))
        batch_op.drop_column('Equip_id')
        batch_op.drop_column('Comment')

    with op.batch_alter_table('equip', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equip_Wc_Descr'))
        batch_op.drop_index(batch_op.f('ix_equip_Num_equi'))

    op.drop_table('equip')
    # ### end Alembic commands ###
