"""avec stat

Revision ID: 105cbb69226e
Revises: 9adcfa39270c
Create Date: 2022-06-24 10:49:45.543750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '105cbb69226e'
down_revision = '9adcfa39270c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Order_Num', sa.String(length=20), nullable=True),
    sa.Column('Description', sa.String(length=100), nullable=True),
    sa.Column('Func_Loc', sa.String(length=30), nullable=True),
    sa.Column('Prio', sa.String(length=10), nullable=True),
    sa.Column('Statututil', sa.String(length=100), nullable=True),
    sa.Column('Statutsys', sa.String(length=100), nullable=True),
    sa.Column('Crea_Date', sa.DateTime(), nullable=True),
    sa.Column('Basic_Start', sa.DateTime(), nullable=True),
    sa.Column('Pdt', sa.String(length=30), nullable=True),
    sa.Column('Annnee', sa.String(length=5), nullable=True),
    sa.Column('Mois', sa.String(length=12), nullable=True),
    sa.Column('Age', sa.String(length=12), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stat', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stat_Age'), ['Age'], unique=False)
        batch_op.create_index(batch_op.f('ix_stat_Annnee'), ['Annnee'], unique=False)
        batch_op.create_index(batch_op.f('ix_stat_Basic_Start'), ['Basic_Start'], unique=False)
        batch_op.create_index(batch_op.f('ix_stat_Crea_Date'), ['Crea_Date'], unique=False)
        batch_op.create_index(batch_op.f('ix_stat_Description'), ['Description'], unique=False)
        batch_op.create_index(batch_op.f('ix_stat_Func_Loc'), ['Func_Loc'], unique=False)
        batch_op.create_index(batch_op.f('ix_stat_Mois'), ['Mois'], unique=False)
        batch_op.create_index(batch_op.f('ix_stat_Order_Num'), ['Order_Num'], unique=False)
        batch_op.create_index(batch_op.f('ix_stat_Pdt'), ['Pdt'], unique=False)
        batch_op.create_index(batch_op.f('ix_stat_Prio'), ['Prio'], unique=False)
        batch_op.create_index(batch_op.f('ix_stat_Statutsys'), ['Statutsys'], unique=False)
        batch_op.create_index(batch_op.f('ix_stat_Statututil'), ['Statututil'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stat', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stat_Statututil'))
        batch_op.drop_index(batch_op.f('ix_stat_Statutsys'))
        batch_op.drop_index(batch_op.f('ix_stat_Prio'))
        batch_op.drop_index(batch_op.f('ix_stat_Pdt'))
        batch_op.drop_index(batch_op.f('ix_stat_Order_Num'))
        batch_op.drop_index(batch_op.f('ix_stat_Mois'))
        batch_op.drop_index(batch_op.f('ix_stat_Func_Loc'))
        batch_op.drop_index(batch_op.f('ix_stat_Description'))
        batch_op.drop_index(batch_op.f('ix_stat_Crea_Date'))
        batch_op.drop_index(batch_op.f('ix_stat_Basic_Start'))
        batch_op.drop_index(batch_op.f('ix_stat_Annnee'))
        batch_op.drop_index(batch_op.f('ix_stat_Age'))

    op.drop_table('stat')
    # ### end Alembic commands ###
