"""avec annee

Revision ID: 50d1fae9ec6f
Revises: 105cbb69226e
Create Date: 2022-06-24 14:02:55.250476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50d1fae9ec6f'
down_revision = '105cbb69226e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Annee', sa.String(length=5), nullable=True))
        batch_op.drop_index('ix_stat_Annnee')
        batch_op.create_index(batch_op.f('ix_stat_Annee'), ['Annee'], unique=False)
        batch_op.drop_column('Annnee')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Annnee', sa.VARCHAR(length=5), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_stat_Annee'))
        batch_op.create_index('ix_stat_Annnee', ['Annnee'], unique=False)
        batch_op.drop_column('Annee')

    # ### end Alembic commands ###
