"""avec equip

Revision ID: 645b08e10562
Revises: 00537577e855
Create Date: 2021-12-30 19:25:27.356648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '645b08e10562'
down_revision = '00537577e855'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=24), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('surname', sa.String(length=32), nullable=True),
    sa.Column('numemploye', sa.String(length=15), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('valide', sa.Boolean(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_numemploye'), ['numemploye'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_surname'), ['surname'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('workcenter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Ticker', sa.String(length=10), nullable=True),
    sa.Column('Wc_Descr', sa.String(length=100), nullable=True),
    sa.Column('Descr_PD', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workcenter', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workcenter_Descr_PD'), ['Descr_PD'], unique=False)
        batch_op.create_index(batch_op.f('ix_workcenter_Ticker'), ['Ticker'], unique=False)
        batch_op.create_index(batch_op.f('ix_workcenter_Wc_Descr'), ['Wc_Descr'], unique=False)

    op.create_table('capac',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Daily', sa.DateTime(), nullable=True),
    sa.Column('Leave', sa.Float(), nullable=True),
    sa.Column('Workcenter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Workcenter_id'], ['workcenter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('capac', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_capac_Daily'), ['Daily'], unique=False)
        batch_op.create_index(batch_op.f('ix_capac_Leave'), ['Leave'], unique=False)

    op.create_table('workorder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Order_Desc', sa.String(length=100), nullable=True),
    sa.Column('Desc_Ordre', sa.String(length=100), nullable=True),
    sa.Column('Order_Num', sa.String(length=20), nullable=True),
    sa.Column('Order_Op', sa.String(length=10), nullable=True),
    sa.Column('Func_Loc', sa.String(length=30), nullable=True),
    sa.Column('Prio', sa.String(length=10), nullable=True),
    sa.Column('Order_Status', sa.String(length=30), nullable=True),
    sa.Column('Est_Hours', sa.Float(), nullable=True),
    sa.Column('Actual_Hours', sa.Float(), nullable=True),
    sa.Column('Crea_Date', sa.DateTime(), nullable=True),
    sa.Column('Basic_Start', sa.DateTime(), nullable=True),
    sa.Column('Workcenter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Workcenter_id'], ['workcenter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workorder', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workorder_Actual_Hours'), ['Actual_Hours'], unique=False)
        batch_op.create_index(batch_op.f('ix_workorder_Basic_Start'), ['Basic_Start'], unique=False)
        batch_op.create_index(batch_op.f('ix_workorder_Crea_Date'), ['Crea_Date'], unique=False)
        batch_op.create_index(batch_op.f('ix_workorder_Desc_Ordre'), ['Desc_Ordre'], unique=False)
        batch_op.create_index(batch_op.f('ix_workorder_Est_Hours'), ['Est_Hours'], unique=False)
        batch_op.create_index(batch_op.f('ix_workorder_Func_Loc'), ['Func_Loc'], unique=False)
        batch_op.create_index(batch_op.f('ix_workorder_Order_Desc'), ['Order_Desc'], unique=False)
        batch_op.create_index(batch_op.f('ix_workorder_Order_Num'), ['Order_Num'], unique=False)
        batch_op.create_index(batch_op.f('ix_workorder_Order_Op'), ['Order_Op'], unique=False)
        batch_op.create_index(batch_op.f('ix_workorder_Order_Status'), ['Order_Status'], unique=False)
        batch_op.create_index(batch_op.f('ix_workorder_Prio'), ['Prio'], unique=False)

    op.create_table('sched',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Daily', sa.DateTime(), nullable=True),
    sa.Column('Plan_hours', sa.Float(), nullable=True),
    sa.Column('Comment', sa.String(length=40), nullable=True),
    sa.Column('equip_id', sa.Integer(), nullable=True),
    sa.Column('Workorder_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Workorder_id'], ['workorder.id'], ),
    sa.ForeignKeyConstraint(['equip_id'], ['equip.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sched', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sched_Comment'), ['Comment'], unique=False)
        batch_op.create_index(batch_op.f('ix_sched_Daily'), ['Daily'], unique=False)
        batch_op.create_index(batch_op.f('ix_sched_Plan_hours'), ['Plan_hours'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sched', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sched_Plan_hours'))
        batch_op.drop_index(batch_op.f('ix_sched_Daily'))
        batch_op.drop_index(batch_op.f('ix_sched_Comment'))

    op.drop_table('sched')
    with op.batch_alter_table('workorder', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workorder_Prio'))
        batch_op.drop_index(batch_op.f('ix_workorder_Order_Status'))
        batch_op.drop_index(batch_op.f('ix_workorder_Order_Op'))
        batch_op.drop_index(batch_op.f('ix_workorder_Order_Num'))
        batch_op.drop_index(batch_op.f('ix_workorder_Order_Desc'))
        batch_op.drop_index(batch_op.f('ix_workorder_Func_Loc'))
        batch_op.drop_index(batch_op.f('ix_workorder_Est_Hours'))
        batch_op.drop_index(batch_op.f('ix_workorder_Desc_Ordre'))
        batch_op.drop_index(batch_op.f('ix_workorder_Crea_Date'))
        batch_op.drop_index(batch_op.f('ix_workorder_Basic_Start'))
        batch_op.drop_index(batch_op.f('ix_workorder_Actual_Hours'))

    op.drop_table('workorder')
    with op.batch_alter_table('capac', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_capac_Leave'))
        batch_op.drop_index(batch_op.f('ix_capac_Daily'))

    op.drop_table('capac')
    with op.batch_alter_table('workcenter', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workcenter_Wc_Descr'))
        batch_op.drop_index(batch_op.f('ix_workcenter_Ticker'))
        batch_op.drop_index(batch_op.f('ix_workcenter_Descr_PD'))

    op.drop_table('workcenter')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_type'))
        batch_op.drop_index(batch_op.f('ix_user_surname'))
        batch_op.drop_index(batch_op.f('ix_user_numemploye'))
        batch_op.drop_index(batch_op.f('ix_user_name'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
