"""avec heurejour

Revision ID: 764711ca7ca0
Revises: 645b08e10562
Create Date: 2022-02-04 07:34:10.479386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '764711ca7ca0'
down_revision = '645b08e10562'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workcenter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Heure_jour', sa.Float(), nullable=True))
        batch_op.create_index(batch_op.f('ix_workcenter_Heure_jour'), ['Heure_jour'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workcenter', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workcenter_Heure_jour'))
        batch_op.drop_column('Heure_jour')

    # ### end Alembic commands ###
