"""avec cgvmsl

Revision ID: 953a63d0479b
Revises: 50d1fae9ec6f
Create Date: 2022-07-01 07:49:08.617547

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '953a63d0479b'
down_revision = '50d1fae9ec6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cgvmsl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Dataname', sa.String(length=20), nullable=True),
    sa.Column('Datemaj', sa.DateTime(), nullable=True),
    sa.Column('Livedata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('Histdata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cgvmsl', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cgvmsl_Dataname'), ['Dataname'], unique=False)
        batch_op.create_index(batch_op.f('ix_cgvmsl_Datemaj'), ['Datemaj'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cgvmsl', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cgvmsl_Datemaj'))
        batch_op.drop_index(batch_op.f('ix_cgvmsl_Dataname'))

    op.drop_table('cgvmsl')
    # ### end Alembic commands ###
