"""enelver capa

Revision ID: 9adcfa39270c
Revises: fa56b80b95d8
Create Date: 2022-02-04 14:04:52.763473

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9adcfa39270c'
down_revision = 'fa56b80b95d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workcenter', schema=None) as batch_op:
        batch_op.drop_index('ix_workcenter_Capa')
        batch_op.drop_column('Capa')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workcenter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Capa', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.create_index('ix_workcenter_Capa', ['Capa'], unique=False)

    # ### end Alembic commands ###
