"""avec capa

Revision ID: fa56b80b95d8
Revises: 8c60426d0de3
Create Date: 2022-02-04 13:56:25.113432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa56b80b95d8'
down_revision = '8c60426d0de3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workcenter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Capa', sa.Float(), nullable=True))
        batch_op.create_index(batch_op.f('ix_workcenter_Capa'), ['Capa'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workcenter', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workcenter_Capa'))
        batch_op.drop_column('Capa')

    # ### end Alembic commands ###
