"""initial

Revision ID: ff0315c51567
Revises: 
Create Date: 2021-12-27 15:01:40.243349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff0315c51567'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=24), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('surname', sa.String(length=32), nullable=True),
    sa.Column('numemploye', sa.String(length=15), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('valide', sa.Boolean(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    op.create_index(op.f('ix_user_numemploye'), 'user', ['numemploye'], unique=False)
    op.create_index(op.f('ix_user_surname'), 'user', ['surname'], unique=False)
    op.create_index(op.f('ix_user_type'), 'user', ['type'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('workcenter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Ticker', sa.String(length=10), nullable=True),
    sa.Column('Wc_Descr', sa.String(length=100), nullable=True),
    sa.Column('Descr_PD', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workcenter_Descr_PD'), 'workcenter', ['Descr_PD'], unique=False)
    op.create_index(op.f('ix_workcenter_Ticker'), 'workcenter', ['Ticker'], unique=False)
    op.create_index(op.f('ix_workcenter_Wc_Descr'), 'workcenter', ['Wc_Descr'], unique=False)
    op.create_table('capac',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Daily', sa.DateTime(), nullable=True),
    sa.Column('Leave', sa.Integer(), nullable=True),
    sa.Column('Workcenter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Workcenter_id'], ['workcenter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capac_Daily'), 'capac', ['Daily'], unique=False)
    op.create_index(op.f('ix_capac_Leave'), 'capac', ['Leave'], unique=False)
    op.create_table('workorder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Order_Desc', sa.String(length=100), nullable=True),
    sa.Column('Desc_Ordre', sa.String(length=100), nullable=True),
    sa.Column('Order_Num', sa.String(length=20), nullable=True),
    sa.Column('Order_Op', sa.String(length=10), nullable=True),
    sa.Column('Func_Loc', sa.String(length=30), nullable=True),
    sa.Column('Prio', sa.String(length=10), nullable=True),
    sa.Column('Order_Status', sa.String(length=30), nullable=True),
    sa.Column('Est_Hours', sa.Integer(), nullable=True),
    sa.Column('Actual_Hours', sa.Integer(), nullable=True),
    sa.Column('Crea_Date', sa.DateTime(), nullable=True),
    sa.Column('Workcenter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Workcenter_id'], ['workcenter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workorder_Actual_Hours'), 'workorder', ['Actual_Hours'], unique=False)
    op.create_index(op.f('ix_workorder_Crea_Date'), 'workorder', ['Crea_Date'], unique=False)
    op.create_index(op.f('ix_workorder_Desc_Ordre'), 'workorder', ['Desc_Ordre'], unique=False)
    op.create_index(op.f('ix_workorder_Est_Hours'), 'workorder', ['Est_Hours'], unique=False)
    op.create_index(op.f('ix_workorder_Func_Loc'), 'workorder', ['Func_Loc'], unique=False)
    op.create_index(op.f('ix_workorder_Order_Desc'), 'workorder', ['Order_Desc'], unique=False)
    op.create_index(op.f('ix_workorder_Order_Num'), 'workorder', ['Order_Num'], unique=False)
    op.create_index(op.f('ix_workorder_Order_Op'), 'workorder', ['Order_Op'], unique=False)
    op.create_index(op.f('ix_workorder_Order_Status'), 'workorder', ['Order_Status'], unique=False)
    op.create_index(op.f('ix_workorder_Prio'), 'workorder', ['Prio'], unique=False)
    op.create_table('sched',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Daily', sa.DateTime(), nullable=True),
    sa.Column('Plan_hours', sa.Integer(), nullable=True),
    sa.Column('Workorder_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Workorder_id'], ['workorder.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sched_Daily'), 'sched', ['Daily'], unique=False)
    op.create_index(op.f('ix_sched_Plan_hours'), 'sched', ['Plan_hours'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sched_Plan_hours'), table_name='sched')
    op.drop_index(op.f('ix_sched_Daily'), table_name='sched')
    op.drop_table('sched')
    op.drop_index(op.f('ix_workorder_Prio'), table_name='workorder')
    op.drop_index(op.f('ix_workorder_Order_Status'), table_name='workorder')
    op.drop_index(op.f('ix_workorder_Order_Op'), table_name='workorder')
    op.drop_index(op.f('ix_workorder_Order_Num'), table_name='workorder')
    op.drop_index(op.f('ix_workorder_Order_Desc'), table_name='workorder')
    op.drop_index(op.f('ix_workorder_Func_Loc'), table_name='workorder')
    op.drop_index(op.f('ix_workorder_Est_Hours'), table_name='workorder')
    op.drop_index(op.f('ix_workorder_Desc_Ordre'), table_name='workorder')
    op.drop_index(op.f('ix_workorder_Crea_Date'), table_name='workorder')
    op.drop_index(op.f('ix_workorder_Actual_Hours'), table_name='workorder')
    op.drop_table('workorder')
    op.drop_index(op.f('ix_capac_Leave'), table_name='capac')
    op.drop_index(op.f('ix_capac_Daily'), table_name='capac')
    op.drop_table('capac')
    op.drop_index(op.f('ix_workcenter_Wc_Descr'), table_name='workcenter')
    op.drop_index(op.f('ix_workcenter_Ticker'), table_name='workcenter')
    op.drop_index(op.f('ix_workcenter_Descr_PD'), table_name='workcenter')
    op.drop_table('workcenter')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_type'), table_name='user')
    op.drop_index(op.f('ix_user_surname'), table_name='user')
    op.drop_index(op.f('ix_user_numemploye'), table_name='user')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
